version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/appuser/app
    volumes:
      - .:/home/appuser/app:delegated
    ports:
      - '8000:8000'
    environment:
      PYTHONUNBUFFERED: '1'
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
