name: Ping SkinAI

on:
  schedule:
    - cron: '*/1 * * * *'  # every 1 minute
  workflow_dispatch:

jobs:
  curl_job:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Both Services
        run: |
          curl -s https://skinai-7wpt.onrender.com/ > /dev/null
          curl -s https://skin-disease-classifier-iiur.onrender.com/ > /dev/null
